/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Panels.asistencia;
import Panels.crud_usuarios;
import Panels.control_asist;
import Panels.informes;

/**
 *
 * @author marce
 */
public class Vista extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Vista.class.getName());

    /**
     * Creates new form vista
     */
    public Vista() {
        initComponents();
        txtID.setVisible(false);
    }
    
    public void mostrarLogin(login l1){
        l1.setSize(1300, 700);
        l1.setLocation(0, 0);
        PanelPrincipal.removeAll();
        PanelPrincipal.add(l1);
        PanelPrincipal.revalidate();
        PanelPrincipal.repaint();
    }
    
    public void mostrarCtrlAsist(control_asist asist){
        asist.setSize(1300, 700);
        asist.setLocation(0, 0);
        PanelPrincipal.removeAll();
        PanelPrincipal.add(asist);
        PanelPrincipal.revalidate();
        PanelPrincipal.repaint();
    }
    
    public void mostrarContenido1(crud_usuarios crud, control_asist as){
        crud.setSize(975, 608);
        crud.setLocation(0, 0);
        as.Contenido.removeAll();
        as.Contenido.add(crud);
        as.Contenido.revalidate();
        as.Contenido.repaint();
    }

    
    public void mostrarAsistencia(asistencia a, control_asist as){
        a.setSize(975, 608);
        a.setLocation(0, 0);
        as.Contenido.removeAll();
        as.Contenido.add(a);
        as.Contenido.revalidate();
        as.Contenido.repaint();
    }
    
    public void mostrarContenido2(informes i , control_asist as){
        i.setSize(975, 608);
        i.setLocation(0, 0);
        as.Contenido.removeAll();
        as.Contenido.add(i);
        as.Contenido.revalidate();
        as.Contenido.repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtID = new javax.swing.JTextField();
        PanelPrincipal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        javax.swing.GroupLayout PanelPrincipalLayout = new javax.swing.GroupLayout(PanelPrincipal);
        PanelPrincipal.setLayout(PanelPrincipalLayout);
        PanelPrincipalLayout.setHorizontalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1293, Short.MAX_VALUE)
        );
        PanelPrincipalLayout.setVerticalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        PanelPrincipal.getAccessibleContext().setAccessibleDescription("re");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Vista().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel PanelPrincipal;
    public javax.swing.JTextField txtID;
    // End of variables declaration//GEN-END:variables
}
